version: '2'
services:
    db:
        image: postgres:13
        restart: always
        env_file:
            - .env
        ports:
            - 5432:5432
        volumes:
            - db_data:/var/lib/postgresql/data
    backend:
        build: .
        volumes:
            - ".:/opt/RAILS_API_BOILERPLATE"
        ports:
            - 3000:3000
        stdin_open: true
        tty: true
        depends_on:
            - db
            - redis
        env_file:
            - .env
    sidekiq:
        build: .
        command: bundle exec sidekiq
        depends_on:
            - db
            - redis
        env_file:
            - .env
    redis:
        image: redis
volumes:
    db_data:
